### ISSUE TITLE
Platform error sensor.jd_price - Integration 'jd_price' not found.

### ISSUE THREAD

**Issue by CodeHuTuTu** [zhujisheng/Home-Assistant-DIY#1]
您好:
在`https://bbs.hassbian.com/thread-960-1-1.html` 下载了这个集成, 不管怎么改, 都是报错
```配置无效

Platform error sensor.jd_price - Integration 'jd_price' not found.```
这个要怎么改呀

**Comment by zhujisheng** [comment]
1. 你这个贴子太古老了，当时的自定义集成文件放置方式与现在有很大区别
2. 自定义集成的问题，最好是问作者
3. 如果你对自定义集成的文件该组织与放置不清楚，可以参考本课程中：《组件接入基础篇》中《自定义组件PulseAudio》和《接入自定义组件——和风天气》，也可以参考《如何开发集成》篇章

**Comment by CodeHuTuTu** [comment]
> 1. 你这个贴子太古老了，当时的自定义集成文件放置方式与现在有很大区别
> 2. 自定义集成的问题，最好是问作者
> 3. 如果你对自定义集成的文件该组织与放置不清楚，可以参考本课程中：《组件接入基础篇》中《自定义组件PulseAudio》和《接入自定义组件——和风天气》，也可以参考《如何开发集成》篇章

好的, 谢谢. 我把课程好好学习一遍
