### ISSUE TITLE
bilibili

### ISSUE THREAD

**Issue by chenpeng1111** [zhujisheng/Home-Assistant-DIY#2]
能否把b站集成

**Comment by zhujisheng** [comment]
What's your meaning of b站集成？

把课程视频放到B站上？还是在HomeAssitant中内看到B站的某些状态？

**Comment by chenpeng1111** [comment]
直接在homeassistant中搜索播放B站的视频

**Comment by chenpeng1111** [comment]
B站

**Comment by zhujisheng** [comment]
内容平台的基本商业逻辑是：不能让自己平台上的内容，在其它平台上播放。因为如果能够这样做的话，平台就没有任何商业价值。
所以这个需求没有意义，即使今天通过某种手段做到了，明天也会被封掉。
